export enum PLAYER_STATUS {
  ACTIVE = "ACTIVE",
  PENDING_PASSWORD = "PENDING_PASSWORD",
  PENDING_ACCOUNT = "PENDING_ACCOUNT",
  PENDING_GALXE = "PENDING_GALXE",
  BANNED = "BANNED"
}

export type PlayerStatus = `${PLAYER_STATUS}`;
